### ISSUE TITLE
how to clear the search box text 

### ISSUE THREAD

**Issue by somya-wittybrains** [srivastavaanurag79/react-native-paper-select#19]
I type something in the search input box and click on the close or done button. If I want to select it again the previously searched text is already there.  How can I clear this up?

@srivastavaanurag79

**Comment by srivastavaanurag79** [comment]
I will fix it and let you know

**Comment by srivastavaanurag79** [comment]
@somya-wittybrains  please upgrade to [`v0.3.7`](https://www.npmjs.com/package/react-native-paper-select/v/0.3.7)

**Comment by somya-wittybrains** [comment]
Thanks @srivastavaanurag79 it works perfectly now.
