### ISSUE TITLE
Long wrapped checkbox label are not aligned

### ISSUE THREAD

**Issue by somya-wittybrains** [srivastavaanurag79/react-native-paper-select#20]
Hi @srivastavaanurag79 

For some check boxes the labels are very long so they were going out of modal width like below: 

![image](https://user-images.githubusercontent.com/99490105/193797421-e10a0112-d788-4ac1-b24c-8e9dbbc357ac.png)

so I tried wrapping them around using
 `checkboxLabelStyle={{
                flex: 1,
                flexWrap: 'wrap'
              }}`

The wrapping of text is working fine but they are not appropriately aligned. 
I have tried applying width, textAlign, selfAlign, flexShrink and other CSS properties but the alignment remains the same.
Here is the image.

![image](https://user-images.githubusercontent.com/99490105/193773217-6fcf06b2-9e35-4d3d-b855-548a5405456a.png)

Could you please have a look and help me with the solution?

**Comment by srivastavaanurag79** [comment]
Will let you know when fixed, I will look into it tomorrow.

**Comment by srivastavaanurag79** [comment]
This should do the trick for now, if you are in a hurry. `checkboxLabelStyle={{flexDirection: 'row', flexShrink: 1}}`. I am adding this in the next release as the default style.

<img width="250" src="https://user-images.githubusercontent.com/24560090/193983317-aef7876f-da21-4b52-8121-f4dade1e13db.png">

**Comment by srivastavaanurag79** [comment]
@somya-wittybrains  published `v0.3.8`

**Comment by somya-wittybrains** [comment]
Hi,
I am facing another related issue. If the labels comprise some lengthy statements there is no space between the current and previous selections. Here is a screenshot of the same.

![image](https://user-images.githubusercontent.com/99490105/196116728-14a1b2c2-7c70-4e0d-9f70-72a8502ef262.png)


The highlighted are two different labels but they look like one single statement.
Could you please have a look and help me with this?
Thanks

**Comment by srivastavaanurag79** [comment]
`checkboxLabelStyle` please use this prop to add custom margin according to your need
