### ISSUE TITLE
There a way to change "Select All" label in multi select mode enabled?

### ISSUE THREAD

**Issue by CarlosSLoureiro** [srivastavaanurag79/react-native-paper-select#23]
I would appreciate if theres a way to change this first item text to my own used language.

<img width="315" alt="image" src="https://user-images.githubusercontent.com/19580424/202926569-ffb360e6-b99d-4da0-a027-02b4febe379f.png">

**Comment by CarlosSLoureiro** [comment]
In addition, would be good if also there's a option to enable or disable the Select All option in multi select mode...

**Comment by srivastavaanurag79** [comment]
Thanks, will let you know when after checking and merging.

**Comment by srivastavaanurag79** [comment]
Any idea how to fix this error ?

<img width="946" alt="image" src="https://user-images.githubusercontent.com/24560090/203492420-fb6d4a3a-5972-42c0-8dfe-f3ae8d021f05.png">


> react-native-paper-select-example@0.0.1 android
> react-native run-android

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 980 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
* daemon not running; starting now at tcp:5037
* daemon started successfully
info Launching emulator...
info Successfully launched emulator.
info Installing the app...
> Task :app:checkDebugDuplicateClasses FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
23 actionable tasks: 3 executed, 20 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform react-native-0.71.0-rc.0-debug.aar (com.facebook.react:react-native:0.71.0-rc.0) to match attributes {artifactType=android-classes, com.android.build.api.attributes.BuildTypeAttr=debug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: C:\Users\sriva\.gradle\caches\modules-2\files-2.1\com.facebook.react\react-native\0.71.0-rc.0\7a7f5a0af6ebd8eb94f7e5f7495e9d9684b4f543\react-native-0.71.0-rc.0-debug.aar.
         > Java heap space

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

**Comment by Thodor12** [comment]
This could be helpful:
https://github.com/facebook/react-native/issues/35210

**Comment by srivastavaanurag79** [comment]
`v 0.3.9` released
