### ISSUE TITLE
More customization

### ISSUE THREAD

**Issue by kdaglas** [srivastavaanurag79/react-native-paper-select#27]
Hey there, really really love this select... i was hoping if there is a way we can customise more of this select, for example reduce the modal box size(height and width), use custom font, for example how the react native paper textInput allows to utilize your custom font...
![pic2](https://user-images.githubusercontent.com/34310682/214304123-e48c2d57-35ed-48d6-95c6-394304643032.jpg)
![pic1](https://user-images.githubusercontent.com/34310682/214304204-a7126fa7-0c59-4c64-925a-9ce5555819f3.jpg)

**Comment by kdaglas** [comment]
i have managed to customize the font in the input box but still figuring out a way to customize the modalbox and its contents

**Comment by srivastavaanurag79** [comment]
is it resolved?
