### ISSUE TITLE
Component is very slow to use on Android

### ISSUE THREAD

**Issue by nicoladj77** [srivastavaanurag79/react-native-paper-select#3]
Hi, I'm using the component with Formik, and it's very slow: it takes a lot to open the dialog and a lot of time when closing the dialog after clicking on Done. I haven't tested on iPhone yet.

**Comment by srivastavaanurag79** [comment]
Sorry, it isn't tested with Formik, works fine natively.

**Comment by nicoladj77** [comment]
@srivastavaanurag79 hey so I think that the issue is only present when a large number of options is being used. I was using 100 options and it was very slow, but with 20 is ok

**Comment by nicoladj77** [comment]
@srivastavaanurag79 good to close but performance should be investigated.

**Comment by nicoladj77** [comment]
@srivastavaanurag79 I am still having performance issue on Android, it's basically slow on first open and on first close. Using it with a list of countries.

**Comment by srivastavaanurag79** [comment]
i am not able to work on this project currently. Sorry

**Comment by srivastavaanurag79** [comment]
Tested for 10000 better optimized now by using flatlist

**Comment by srivastavaanurag79** [comment]
optimized version released v1.3.0 based on shopify flash list
