### ISSUE TITLE
Feature Needed: Support to be able to have Checkbox.android on ios 

### ISSUE THREAD

**Issue by sufyansalim** [srivastavaanurag79/react-native-paper-select#45]
It would be nice to have this feature to have react native paper Checkbox Android on iOs as iphone has this weird tick sign instead for a default checkbox .

` <Checkbox.Android
      status={checked ? 'checked' : 'unchecked'}
      onPress={() => {
        setChecked(!checked);
      }}
    />`

**Comment by srivastavaanurag79** [comment]
Ok will let you know when released

**Comment by srivastavaanurag79** [comment]
Sorry, in React Native Paper, the Checkbox.Android component is specifically designed for Android, and there is also a Checkbox.IOS component for iOS. If you use Checkbox.Android on an iOS device, it won't render as expected, and you may face compatibility issues.
