### ISSUE TITLE
outlineColor in textInputProps is not working in iOs, but working fine in android

### ISSUE THREAD

**Issue by nicoladj77** [srivastavaanurag79/react-native-paper-select#48]
I have the following select, the issue is that the  outlineColor in textInputProps is ignored, it is always black

 <PaperSelect
                      value={values.country}
                      onSelection={(value) => {
                        handleChange('country')(value.text);
                      }}
                      arrayList={countryList}
                      textInputMode="outlined"
                      selectedArrayList={[]}
                      errorText=""
                      activeOutlineColor={style.selectedOuterInput}
                      multiEnable={false}
                      checkboxProps={{
                        checkboxColor: style.selectedOuterInput,
                        checkboxLabelStyle: { color: 'black' },
                      }}
                      textInputProps={{
                        activeOutlineColor: style.selectedOuterInput,
                        outlineColor: getOutlineColor(
                          errors,
                          touched,
                          'country',
                          style,
                        ),
                      }}
                    />

**Comment by srivastavaanurag79** [comment]
i think this will do it (#44) 

`textInputOutlineStyle` => you will need to upgrade the react native paper to v5  for it work
