### ISSUE TITLE
Use Paper theme by default

### ISSUE THREAD

**Issue by WillSmithTE** [srivastavaanurag79/react-native-paper-select#49]
I thought this package would use PaperProvider theme by default, and while technically it does, it also overrides styles meaning the theme is ignored.

E.g. I use`MD3DarkTheme` for dark mode, but the styling for the TextInput is overridden because it uses its own styles. 

```
textInput: {
    backgroundColor: '#fff',
    color: '#000',
  },
```

[here](https://github.com/srivastavaanurag79/react-native-paper-select/blob/master/src/module/paperSelect.tsx#L356C3-L359C5)

Is this intentional? Would you accept a PR to change it? 

Same for the dialog background color

**Comment by WillSmithTE** [comment]
Similarly, if we could import Text from `react-native-paper` [here](https://github.com/srivastavaanurag79/react-native-paper-select/blob/master/src/components/checkBox.tsx#L2C31-L2C31) we'd keep the theme

**Comment by GunnarAK** [comment]
This is also the case for the dialog portion. The backgroundColor is set to `white` and is not inheriting the app theme.

https://github.com/srivastavaanurag79/react-native-paper-select/blob/master/src/module/paperSelect.tsx#L375
```
const styles = StyleSheet.create({
  container: {
    width: '100%',
    marginBottom: 10,
  },
  dialog: {
    backgroundColor: 'white',      <-----
    borderRadius: 5,
  },
  ...
```

Temp fix is setting the `dialogStyle={{backgroundColor: colorScheme === "dark" ? "YOUR_DARK_COLOR" : "YOUR_LIGHT_COLOR"}}` prop on your `<PaperSelect />` component.

**Comment by srivastavaanurag79** [comment]
will fix it in next update

**Comment by srivastavaanurag79** [comment]
@himrocks33 Please fix this in your merge request also
