### ISSUE TITLE
first click on android doesn't work

### ISSUE THREAD

**Issue by NahumG10** [srivastavaanurag79/react-native-paper-select#5]
Every time I open the dialog in android device, first time I click on an option, it isn't being picked but on the second click it works flawless. Is there a fix for it?

**Comment by srivastavaanurag79** [comment]
I will test it and let you know.

**Comment by srivastavaanurag79** [comment]
Found the issue its something to do with the dynamic rendering of the checkboxes, I will let you know when fixed.

**Comment by srivastavaanurag79** [comment]
@Bo7mid3 can you look into this issue?

**Comment by Bo7mid3** [comment]
> @Bo7mid3 can you look into this issue?

fixed

**Comment by srivastavaanurag79** [comment]
@NahumG10 issue fixed, install the latest v0.3.0.
