### ISSUE TITLE
Modal Close Button Text width

### ISSUE THREAD

**Issue by wonderer007** [srivastavaanurag79/react-native-paper-select#54]
How can I adjust Modal close button width

<img width="352" alt="Screenshot 2024-02-21 at 11 21 52 PM" src="https://github.com/srivastavaanurag79/react-native-paper-select/assets/2243326/929dfede-17cc-4cd2-86e0-01b98a723983">

```
"react-native": "0.68.2"
"react-native-paper-select": "^1.1.0"
```

**Comment by srivastavaanurag79** [comment]
`dialogCloseButtonStyle` is this not working ?
