### ISSUE TITLE
Using testID

### ISSUE THREAD

**Issue by ioteecs-team** [srivastavaanurag79/react-native-paper-select#55]
Hi,

Unfortunately, there is no testID that can be provided to enable the use of testing solutions.

Is it possible to add testID support ?

Cheers,
Luc

**Comment by srivastavaanurag79** [comment]
[v1.2.0](https://www.npmjs.com/package/react-native-paper-select/v/1.2.0)

Test Props:
| Name                     | Description                          |
| ------------------------ | ------------------------------------ |
| testID                   | test id for paper select             |
| dialogTestID             | test id for dialog box               |
| searchbarTestID          | test id for search bar in dialog box |
| selectAllCheckboxTestID  | test id for select all in dialog     |
| itemCheckboxTestIDPrefix | Prefix for item checkbox test id (default: 'checkbox-')  |

checkbox testId would look like this => ``` testID={`${itemCheckboxTestIDPrefix}${item._id}`} ``` where item._id is the id of the items
