### ISSUE TITLE
tsc compile error in `src/interface/paperSelect.interface.ts`

### ISSUE THREAD

**Issue by vpume** [srivastavaanurag79/react-native-paper-select#60]
We are using `src/interface/paperSelect.interface.ts` in our ci/cd pipeline to make sure that there are no unused variables etc. in our react native application. 

This emits the following error:

```
> npx tsc --noEmit -p . --pretty

node_modules/react-native-paper-select/src/interface/paperSelect.interface.ts:4:32 - error TS2307: Cannot find module 'react-native-paper/lib/typescript/src/types' or its corresponding type declarations.

4 import type { ThemeProp } from 'react-native-paper/lib/typescript/src/types';
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/react-native-paper-select/src/interface/paperSelect.interface.ts:4
```

We are using V1.1.1 of `react-native-paper-select`, together with V5.12.3 of `react-native-paper`

If I change `import type { ThemeProp } from 'react-native-paper/lib/typescript/src/types';` in `paperSelect.interface.ts` to `import { ThemeProp } from 'react-native-paper/lib/typescript/types';`, no compile error occurs anymore

**Comment by srivastavaanurag79** [comment]
will fix the import in next update

**Comment by srivastavaanurag79** [comment]
Please install `v1.1.2`
https://www.npmjs.com/package/react-native-paper-select/v/1.1.2
