### ISSUE TITLE
PaperSelect inside a Modal

### ISSUE THREAD

**Issue by Killouis** [srivastavaanurag79/react-native-paper-select#61]
Hi there,
I think I have some problems to open the select modal inside another modal, because when I click on select it doesn't open anything.
This is my code:
```typescript
    <Portal>
      <Modal visible={visible} animationType="slide">
        <ScrollView>
          <PaperSelect />
        </ScrollView>
        <Toast />
      </Modal>
    </Portal>
```

**Comment by srivastavaanurag79** [comment]
I don't think it would work inside a modal, because it itself opens a modal.

**Comment by Killouis** [comment]
I see... so i think i should turn the modal into a view. Thank you for the answer!

**Comment by srivastavaanurag79** [comment]
> I see... so i think i should turn the modal into a view. Thank you for the answer!

Yes, that will do.
