### ISSUE TITLE
PaperSelect error styling

### ISSUE THREAD

**Issue by amanvision** [srivastavaanurag79/react-native-paper-select#62]
I have 2 inputs
1. PaperSelect 
2. TextInput from react-native-paper
( see attached screenshot )
![image](https://github.com/user-attachments/assets/f8cc1150-ed32-486a-9115-d71b0661443b)

I wanted to style the error state for PaperSelect the same as TextInput from react-native-paper
I'm able to set border color, but not able to set color on label 

react-native-paper-select: 1.1.1
react-native-paper: 5.12.3

It will better to have error prop like TextInput: https://callstack.github.io/react-native-paper/docs/components/TextInput/#error

**Comment by srivastavaanurag79** [comment]
making it default if there would be error `error={errorText && errorText?.length > 0 ? true : false}` it will automatically take react native paper default error color etc.

[react-native-paper/docs/components/TextInput/#error](https://callstack.github.io/react-native-paper/docs/components/TextInput/#error)
```
error
Type: boolean

Default value: false

Whether to style the TextInput with error style.
```

**Comment by srivastavaanurag79** [comment]
<img src="https://github.com/user-attachments/assets/34c0b610-1a48-4dd2-a4d3-d8f9489f237c" width="300"/>

**Comment by srivastavaanurag79** [comment]
Please install `v1.1.2`
https://www.npmjs.com/package/react-native-paper-select/v/1.1.2
