### ISSUE TITLE
Close Dropdown Automatically on Selection When multipleEnable is false

### ISSUE THREAD

**Issue by amanvision** [srivastavaanurag79/react-native-paper-select#64]
Currently, when multipleEnable is set to false, the dropdown does not close automatically after a selection is made. This behavior can be improved to enhance user experience.

Feature Request:
-  Feature: If multipleEnable is false, the dropdown should close automatically after a selection is made.
-  Current Behavior: The dropdown remains open after a single selection.
-  Expected Behavior: The dropdown should automatically close after a selection is made, making it more intuitive for single-selection use cases.

Use Case
When using the dropdown in single-selection mode, users expect the dropdown to close immediately after a choice is made. This would streamline the user interface and improve usability.

**Comment by amanpaix** [comment]
@srivastavaanurag79

**Comment by srivastavaanurag79** [comment]
Sorry, I am not able to work on this project currently, as I am engaged in some other work for 2-3 months.

**Comment by amanvision** [comment]
Yes, Right!

**Comment by srivastavaanurag79** [comment]
Please install `v1.1.2`
https://www.npmjs.com/package/react-native-paper-select/v/1.1.2
