### ISSUE TITLE
Hook to change or add functionality to onPress

### ISSUE THREAD

**Issue by OOCAZ** [srivastavaanurag79/react-native-paper-select#67]
Hello!

I am using this library with a team, and we are looking to run some custom functionality when the multiSelect is pressed. For us specifically we are looking to dismiss the keyboard if it is up, when the input is clicked in order to not obscure any of the modal with the possible selections. 

To replicate this simply have a textInput on the same page and click into it on mobile thus opening the keyboard and then click on the multiSelect. In our experience the keyboard is staying open and then obscuring some of the modal.

If there is already a functionality for this or a better way of doing this, please feel free to let me know and I will close immediately.

**Comment by srivastavaanurag79** [comment]
There is a patch for the test case you described I will have to explicitly close the keyboard (if opened) when the multi select textinput is clicked so that the keyboard doesn't obstruct multiselect modal.

`import { Keyboard } from 'react-native';`

`Keyboard.dismiss();` this will be the first line in the onFocus of the source code which will close the keyboard. 

i will add above code in the next release.


Currently, you can wrap your code in a view or touchable which triggers this behaviour maybe that would help

**Comment by srivastavaanurag79** [comment]
You can use the inputRef prop. (Patch)

```
import React, { useRef, useEffect } from 'react';
import { View, TextInput, Keyboard } from 'react-native';
import PaperSelect from 'react-native-paper-select';

const MyComponent = () => {
  // Create a ref for the PaperSelect input
  const inputRef = useRef(null);

  useEffect(() => {
    if (inputRef.current) {
      // Add a focus listener to the ref's current input
      const handleFocus = () => {
        Keyboard.dismiss(); // Dismiss the keyboard when PaperSelect gains focus
      };

      const inputElement = inputRef.current;
      inputElement.addEventListener('focus', handleFocus);

      // Cleanup listener on unmount
      return () => {
        inputElement.removeEventListener('focus', handleFocus);
      };
    }
  }, []);

  return (
    <View style={{ flex: 1, padding: 16 }}>
      <TextInput placeholder="Type here" style={{ marginBottom: 20 }} />
      <PaperSelect
        multiSelect
        label="Select Options"
        inputRef={inputRef} // Pass the ref to PaperSelect
        onSelection={(value) => {
          console.log('Selected Value:', value);
        }}
        // Add other props as needed
      />
    </View>
  );
};

export default MyComponent;
```

**Comment by OOCAZ** [comment]
Thank you for the quick response! Wonderful work, looking forward to the next release.

**Comment by srivastavaanurag79** [comment]
Fix released:
[v1.2.1](https://www.npmjs.com/package/react-native-paper-select/v/1.2.1)
