### ISSUE TITLE
I can't set default multi value can you help please

### ISSUE THREAD

**Issue by chhorvon** [srivastavaanurag79/react-native-paper-select#7]
![Screenshot 2022-06-10 at 3 56 08 pm](https://user-images.githubusercontent.com/31352266/173030030-de29e62d-68c4-4501-bd79-9ba9c57d3ead.png)
![Screenshot 2022-06-10 at 3 56 26 pm](https://user-images.githubusercontent.com/31352266/173030045-d318c2e9-2652-4bbd-b4d1-e3295ba275b0.png)

**Comment by chhorvon** [comment]
<img width="406" alt="Screenshot 2022-06-10 at 4 02 30 pm" src="https://user-images.githubusercontent.com/31352266/173031154-5c111aa6-cdb6-484f-b264-8ef70004d29f.png">

**Comment by srivastavaanurag79** [comment]
use this currently:
let selected: Array<any> = [];
    selectedData.forEach((val) => {
      data.forEach((el) => {
        if (val._id === el._id) {
          selected.push(el.value);
        }
      });
    });
    value = selected.join();
    
    will fix and update it

**Comment by srivastavaanurag79** [comment]
v0.2.1 published
