### ISSUE TITLE
I can not find the outline text color change option

### ISSUE THREAD

**Issue by jaamaalxyz** [srivastavaanurag79/react-native-paper-select#9]
is there any way to change the outline color

![image](https://user-images.githubusercontent.com/20262255/183877917-7e78947f-b0bd-4eb8-864d-b9f5bb4baa26.png)

The above screenshot I would like to change the `Select Payment Type` color to `white`

**Comment by srivastavaanurag79** [comment]
try this [React Native Paper Text Input default props](https://callstack.github.io/react-native-paper/text-input.html) 
will add custom key in the next update

**Comment by srivastavaanurag79** [comment]
@Thodor12 can you look into this one ?

**Comment by Thodor12** [comment]
> @Thodor12 can you look into this one ?

I will a bit later when I'm done with work for the day, this doesn't look like a particularly difficult one

**Comment by Thodor12** [comment]
This is a bug with react native paper it's TextInput component, in testing I found that the outline colour does not affect the label text, it only works when the component is focused.

Please forward this issue to https://github.com/callstack/react-native-paper/issues

**Comment by srivastavaanurag79** [comment]
> This is a bug with react native paper it's TextInput component, in testing I found that the outline colour does not affect the label text, it only works when the component is focused.

Yes, that is what I found whatever colour one uses it only affects when it's focused.

**Comment by Thodor12** [comment]
Unfortunately I do not see a simple solution for this, I could overwrite the styles to force the label to show correctly, but that gives problems as I cannot detect if the input is "active" or not, so I could not change the styles based on that.

This would have to be fixed in react-native-paper first

**Comment by srivastavaanurag79** [comment]
@jaamaalxyz [Please try this method.]( https://github.com/callstack/react-native-paper/issues/3339#issuecomment-1250803776). Please go through this method once.

```
<TextInput
    mode="outlined"
    label="Outlined input"
    placeholder="Type something"
	// it will change the color of the label, placeholder and inactive outline
    theme={{
      colors: {
        placeholder: 'white',
      },
    }}
	// it will change the inactive outline color
    outlineColor="green"
  />
```

**Comment by jaamaalxyz** [comment]
Yes, I have tested your given solutions and they work. thanks

**Comment by jaamaalxyz** [comment]
![Screenshot_2022_0919_163056.jpg](https://user-images.githubusercontent.com/20262255/190999066-6c79799a-30cf-40c6-8ba0-535bb175b466.jpg)
